language:
  php

php:
  - '7.0.8'
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit tests/ -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/coveralls
